name: Build Firmware

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware-bin
          path: .pio/build/esp32s3/firmware.bin
